apiVersion: v1
kind: Secret
metadata:
  name: fcg-payments-secret
type: Opaque
stringData:
  FCG_DB_CONNECTION_STRING: "${FCG_DB_CONNECTION_STRING}"
  FCG_SERVICEBUS_CONNECTION_STRING: "${FCG_SERVICEBUS_CONNECTION_STRING}"
  NEW_RELIC_LICENSE_KEY: "${NEW_RELIC_LICENSE_KEY}"
